import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SVG render bug demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

const TextStyle font1 = TextStyle(
  fontFamily: 'SourceSansPro',
  fontWeight: FontWeight.w500,
  fontStyle: FontStyle.normal,
  fontSize: 20,
);
const TextStyle font2 = TextStyle(
  fontFamily: 'SourceSansPro',
  fontWeight: FontWeight.w600,
  fontStyle: FontStyle.normal,
  fontSize: 20,
);
const TextStyle font3 = TextStyle(
  fontFamily: 'SourceSansPro',
  fontWeight: FontWeight.w700,
  fontStyle: FontStyle.normal,
  fontSize: 20,
);
const TextStyle font4 = TextStyle(
  fontFamily: 'SourceSerifPro',
  fontWeight: FontWeight.w500,
  fontStyle: FontStyle.italic,
  fontSize: 20,
);
const TextStyle font5 = TextStyle(
  fontFamily: 'SourceSerifPro',
  fontWeight: FontWeight.w600,
  fontStyle: FontStyle.normal,
  fontSize: 20,
);
const TextStyle font6 = TextStyle(
  fontFamily: 'SourceSerifPro',
  fontWeight: FontWeight.w500,
  fontStyle: FontStyle.italic,
  fontSize: 20,
);

Widget svgItems() => Wrap(children: [
      Text("lorem ipsum dolor äöüß", style: font1),
      Text("lorem ipsum dolor äöüß", style: font2),
      Text("lorem ipsum dolor äöüß", style: font3),
      Text("lorem ipsum dolor äöüß", style: font4),
      Text("lorem ipsum dolor äöüß", style: font5),
      Text("lorem ipsum dolor äöüß", style: font6),
      SvgPicture.asset('assets/food/?.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/a.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/acorn.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/alcohol-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/almond.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/amaretini.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ananas.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/anise.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/apple.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/apple.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/artichoke.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/asparagus.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/avocado.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/b.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bacon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/baguette.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/baking.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/banana.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/banana.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/barbeque.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/beef-grill.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/beef-raw.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/beef3.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/beer-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/beer-mug.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/biltong.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/blueberries.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/boiled-egg.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bonbon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bowl.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bread.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/breakfast.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/brezel.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/broccoli.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bun.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/bunny.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/butcher.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/butter.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/c.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cabbage.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cake-slice.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cake.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/calf-steak.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/can.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cancer-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/carrot.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/carrot.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/carton-tetra-oplate.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/carton-tetra-small.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/carton-tetra.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cashew.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/celery.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cheese.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cherry-tomato.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cherry.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cherry.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chestnut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chewing-gum.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chicken-breast.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chicken-leg.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chicken.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chili.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chilled-champagne.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chilly.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chinese-lettuce.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/chocolate.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/clove.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/coce-with-glass.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cocoa-pod.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/coconut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/coffee-filter.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cookie.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cores.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/corn.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/couverture.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cow.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/croissant.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cucumber-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cucumber.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cucumbers-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/cucumbers-cut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/d.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/deer.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/diaper.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/donut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/duck.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/durian.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/e.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/egg-holder.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/eggplant.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/f.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/feeding-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/fennel.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/figs.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/fish.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/french-fries.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/fresh-pasta.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/fried-egg.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/frosted.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/fruits.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/g.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/garlic.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/generic-vegetables.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/gherkin.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ginger.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/grain.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/grape.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/grill.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/gummy-bear.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/h.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ham.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hamburger.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/haricot.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hazelnut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/herb-knife.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/honeymelon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/horseradish.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hot-drink-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hot-drink.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hot-sauce.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hotdog.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/hotdog.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/i.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/icecream.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/icecream.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/j.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/jar-glass.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/jar-side.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/jar-taxseal.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/jar.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/juice.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/k.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/kaki.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/kitchen-roll.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/kiwi.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/l.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ladle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/leaves-jagged.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/leaves.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/lebkuchen.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/lemon.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/lemon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/lettuce.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/limonade-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/liqour.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/liquid-soap.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/little-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/little-things.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/m.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/macis.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/maize.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/mango.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/maple.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/marshmallow.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/marzipan.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/melon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/milchschnitte.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/milk.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/mortar-and-pestle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/muffin-tins.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/mug.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/mushroom.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/muuton.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/n.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/nuts.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/o.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/olive-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/olive-oil-pot.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/olive.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/onion.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/orange.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/p.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pan.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/papaya.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/paprika.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/party-cake.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pasta.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pastic-box.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pea.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/peach.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/peach.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/peanut.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pear.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pear.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pecan.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pepper-pot-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pepper.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pet-bottle.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pet-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pie.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pig.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pistachio.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pizza-slice.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pizza-slice.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pizza.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/plastic-bag-packaging.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/plastic-cup-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/plastic-cup-low.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/plastic-cup-quark.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/plum.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pomegranate.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pot-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pot-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/potato.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/potatoe-chips.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/prawn.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/pumpkin.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/q.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/r.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/rabbit.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/rabit.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/radish.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/raspberry.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/rice-waffle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/roasted-chicken.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/rolling-pin.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/s.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/salami-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/salami-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/salmon.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/salt-pepper.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/salt-pot.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sandwich.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sardines.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sauce-boat.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sauce-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sauce.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sausage.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/schokokuss.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sheep.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/shell-1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/shot-glasses.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sieve.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/small-paper.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/soup.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/soup.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/soy-sauce.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/spa-oil-glass-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/spekulatius.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/spice.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/spinach.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/spring-onion.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sprouts.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/steak.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/stevia.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/strawberry.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sugar-bowl.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sunflower-seed.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sushi.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/sweet-potato.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/t.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/taurus-2.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tea-mug.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/toast.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tofu.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/toilet-paper.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tomato.1.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tomato.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/transparent-bag.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/trash-bag.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tube.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/tulip.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/u.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/v.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/vanilla.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/vegetables.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/w.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/waffles.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/whip-cream.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/whipped-cream.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/white-radish.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/wine-bottle.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/wine-glass.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/wraps.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/x.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/y.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/yagermeister.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/z.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/zucchini.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ä.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ö.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/ü.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/addInverse_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/add_120px.svg',
          color: Colors.black, width: 120.0, height: 120.0),
      SvgPicture.asset('assets/interface/add_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/back_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/checkInverse_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/checkOff_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/checkOn_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/check_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronDown_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronThinDown_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronThinRight_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/clock_16px.svg',
          color: Colors.black, width: 16.0, height: 16.0),
      SvgPicture.asset('assets/interface/deleteInverse_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/deleteSimple_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/delete_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/delete_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/duplicate_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/edit_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/edit_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/escape_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/floatingButton_60px.svg',
          width: 60.0, height: 60.0),
      SvgPicture.asset('assets/interface/menu_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/microphone_40px.svg',
          color: Colors.black, width: 40.0, height: 30.0),
      SvgPicture.asset('assets/interface/more_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/remove_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/submit_40px.svg',
          color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/trash_30px.svg',
          color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/undo_24px.svg',
          color: Colors.black, width: 24.0, height: 24.0),
    ]);

List getItems(num) {
  List items = <Widget>[];
  for (var i = 0; i < num; i++) {
    items..add(svgItems());
  }
  return items;
}

void _showDialog(BuildContext context) {
  // flutter defined function
  showDialog(
    context: context,
    builder: (BuildContext context) {
      // return object of type Dialog
      return AlertDialog(
        content: SingleChildScrollView(
            child: Wrap(
          children: getItems(1),
        )),
        actions: <Widget>[
          // usually buttons at the bottom of the dialog
          new FlatButton(
            child: Text('Close'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
        ],
      );
    },
  );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        brightness: Brightness.light,
        title: Text('SVG render bug demo'),
      ),
      body: Padding(
        padding: EdgeInsets.all(20),
        child: SingleChildScrollView(
          child: GestureDetector(
              onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => MySecondPage()),
                  ),
              child: Wrap(
                children: getItems(1),
              )),
        ),
      ),
    );
  }
}

class MySecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.black,
        brightness: Brightness.dark,
        title: Text('SVG render bug demo'),
      ),
      body: Padding(
        padding: EdgeInsets.all(20),
        child: SingleChildScrollView(
          child: GestureDetector(
              onTap: () => _showDialog(context),
              child: Wrap(
                children: getItems(1),
              )),
        ),
      ),
    );
  }
}
