import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SVG render bug demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

Widget svgItems() =>
    Wrap(children: [
      SvgPicture.asset('assets/food/?.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/A.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Acorn.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Alcohol-1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Almond.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ananas.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Apple.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Apple.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Artichoke.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Asparagus.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Avocado.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/B.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Baguette.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Baking.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Banana.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Banana.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Barbeque.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Beef3.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Beer Mug.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Blueberries.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Boiled Egg.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Bread.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Breakfast.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Broccoli.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Bunny.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Butcher.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Butter.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/C.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cabbage.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cake Slice.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cancer 2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Carrot.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Carrot.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cashew.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Celery.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cheese.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cherry Tomato.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cherry.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cherry.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chicken leg.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chicken.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chili.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chilled Champagne.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chilly.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chinese Lettuce.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Chocolate.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Clove.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Coce with Glass.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cocoa Pod.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Coconut.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cookie.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Corn.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cow.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Croissant.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cucumber-2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cucumber.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Cucumbers-2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/D.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Deer.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Diaper.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Donut.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Duck.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Durian.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/E.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Egg Holder.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Eggplant.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/F.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Feeding Bottle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Fennel.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Figs.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Fish.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/French Fries.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Fried Egg.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Frosted.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Fruits.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/G.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Garlic.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Gherkin.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ginger.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Grain.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Grape.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Grill.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/H.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ham.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hamburger.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Haricot.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hazelnut.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Herb Knife.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Honeymelon.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hot Drink 1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hot Sauce.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hot drink.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hotdog.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Hotdog.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/I.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Icecream.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Icecream.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/J.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Jar Glass.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Jar.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Juice.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/K.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Kiwi.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/L.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ladle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Lemon.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Lemon.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Lettuce.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Limonade 1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Liqour.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Liquid Soap.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/M.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Maize.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Mango.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Melon.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Microphone.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Milk.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Mortar And Pestle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Mug.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Mushroom.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/N.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Nuts.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/O.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Olive Oil Pot.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Olive-2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Olive.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Onion.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Orange.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/P.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pan.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Papaya.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Paprika.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Party Cake.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pasta.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pea.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Peach.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Peach.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Peanut.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pear.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pear.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pecan.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pepper Pot 1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pepper.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pet Bottle.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pet Bottle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pie.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pig.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pistachio.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pizza Slice.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pizza Slice.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pizza.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Plum.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pomegranate.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pot 1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pot 2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Potato.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Potatoe Chips.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Prawn.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Pumpkin.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Q.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/R.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Rabbit.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Rabit.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Radish.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Raspberry.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Roasted Chicken.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Rolling Pin.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/S.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Salami-1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Salami-2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Salmon.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Salt Pepper.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Salt Pot.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sandwich.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sardines.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sauce Boat.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sauce Bottle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sauce.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sausage.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sheep.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Shot Glasses.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sieve.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Small Tin.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Soup.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Soup.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Soy Sauce.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Spa oil glass 2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Spice.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Spinach.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Steak.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Strawberry.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sugar Bowl.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sunflower Seed.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sushi.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Sweet Potato.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/T.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Taurus 2.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Tea Mug.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Toast.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Toilet Paper.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Tomato.1.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Tomato.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Tulip.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/U.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/V.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Vegetables.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/W.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Whip Cream.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Whipped Cream.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/White Radish.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Wine Bottle.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Wine Glass.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/X.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Y.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Yagermeister.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Yogurt.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Z.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Zucchini.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ä.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ö.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/food/Ü.svg', color: Colors.black, width: 30.0, height: 30.0),

      SvgPicture.asset('assets/interface/addInverse_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/add_120px.svg', color: Colors.black, width: 120.0, height: 120.0),
      SvgPicture.asset('assets/interface/add_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/back_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/checkInverse_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/checkOff_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/checkOn_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/check_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronDown_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronThinDown_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/chevronThinRight_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/clock_16px.svg', color: Colors.black, width: 16.0, height: 16.0),
      SvgPicture.asset('assets/interface/deleteInverse_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/deleteSimple_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/delete_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/delete_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/duplicate_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/edit_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/edit_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/escape_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/floatingButton_60px.svg', width: 60.0, height: 60.0),
      SvgPicture.asset('assets/interface/menu_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/microphone_40px.svg', color: Colors.black, width: 40.0, height: 30.0),
      SvgPicture.asset('assets/interface/more_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
      SvgPicture.asset('assets/interface/remove_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/submit_40px.svg', color: Colors.black, width: 40.0, height: 40.0),
      SvgPicture.asset('assets/interface/trash_30px.svg', color: Colors.black, width: 30.0, height: 30.0),
      SvgPicture.asset('assets/interface/undo_24px.svg', color: Colors.black, width: 24.0, height: 24.0),
    ]);

List getItems(num) {
  List items = <Widget>[];
  for (var i = 0; i < num; i++) {
    items..add(svgItems());
  }
  return items;
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('SVG render bug demo'),
      ),
      body: Padding(
        padding: EdgeInsets.all(20),
        child: SingleChildScrollView(
          child: Wrap(
            children: getItems(1),
          ),
        ),
      ),
    );
  }
}
